import { AbilityConstant, ConfigurationConstant, UIAbility, Want } from '@kit.AbilityKit';
import { hilog } from '@kit.PerformanceAnalysisKit';
import { window } from '@kit.ArkUI';
import { PrefsUtil } from '../common/PrefsUtil';
import { AgcInitializer } from '../service/AgcInitializer';
import { LocalUserService } from '../service/LocalUserService';
import { AccountService } from '../service/AccountService';
import { SpaceRepository } from '../repository/SpaceRepository';
import { RecipeStatsRepository } from '../repository/RecipeStatsRepository';
import { FavoriteRepository } from '../repository/FavoriteRepository';
import { LikeRepository } from '../repository/LikeRepository';

const DOMAIN = 0x0000;

export default class EntryAbility extends UIAbility {
  onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): void {
    try {
      this.context.getApplicationContext().setColorMode(ConfigurationConstant.ColorMode.COLOR_MODE_NOT_SET);
    } catch (err) {
      hilog.error(DOMAIN, 'testTag', 'Failed to set colorMode. Cause: %{public}s', JSON.stringify(err));
    }
    PrefsUtil.init(this.context);
    AccountService.initStorage();
    LocalUserService.initStorage();
    SpaceRepository.getInstance().initStorage();
    SpaceRepository.getInstance().ensureLocalCoupleSpace();
    RecipeStatsRepository.getInstance().initStorage();
    FavoriteRepository.getInstance().initStorage();
    LikeRepository.getInstance().initStorage();
    AgcInitializer.init(this.context);
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onCreate');
  }

  onDestroy(): void {
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onDestroy');
  }

  onWindowStageCreate(windowStage: window.WindowStage): void {
    // Main window is created, set main page for this ability
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onWindowStageCreate');

    windowStage.loadContent('pages/Index', (err) => {
      if (err.code) {
        hilog.error(DOMAIN, 'testTag', 'Failed to load the content. Cause: %{public}s', JSON.stringify(err));
        return;
      }
      hilog.info(DOMAIN, 'testTag', 'Succeeded in loading the content.');
    });
  }

  onWindowStageDestroy(): void {
    // Main window is destroyed, release UI related resources
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onWindowStageDestroy');
  }

  onForeground(): void {
    // Ability has brought to foreground
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onForeground');
  }

  onBackground(): void {
    // Ability has back to background
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onBackground');
  }
}